name: Deploy backend

on:
  push:
    paths: 
    - 'backend/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'backend/**'
    branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Use node
          uses: actions/setup-node@v4
          with:
            node-version: 20.16.0
            cache: 'npm'
            cache-dependency-path: "**/package-lock.json"
        - name: Delete node_modules
          run: rm -rf node_modules
          

        - name: Install Dependencies
          run: npm install
          working-directory: ./backend

        - name: Deploy to OCI VM
          uses: appleboy/scp-action@master
          with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              port: ${{secrets.SSH_PORT}}
              source: "./backend/*"
              target: ${{secrets.WORKING_DIR}}/backend/

        - name: Restart service
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              sudo systemctl restart ${{ secrets.SERVICE_NAME }}
              

