name: Deploy backend

on:
  push:
    paths: 
    - 'backend/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'backend/**'
    branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Use node
          uses: actions/setup-node@v4
          with:
              node-version: 20.16.0
              cache: 'npm'
              run: npm cache clean --force
        - name: Delete node_modules
          run: rm -rf node_modules
          

        - name: Install Dependencies
          run: npm install
          working-directory: ./backend/

        - name: Deploy to OCI VM
          uses: appleboy/scp-action@master
          with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              port: ${{secrets.SSH_PORT}}
              source: "./backend/**"
              target: ${{secrets.WORKING_DIR}}
